### ISSUE TITLE
Expand recursively

### ISSUE THREAD

**Issue by badboy** [llogiq/overflower#4]
Currently this code:

```rust
#[overflow(wrap)]
fn main() {
    let i = 1u8 - 1 - 2;
}
```

expands to:

```rust
fn main() { 
    let i = 1u8 - 1.sub_wrap(2);
}
```

This is because in [`tag_method`](https://github.com/llogiq/overflower/blob/master/src/lib.rs#L105) the receiver is noop-folded.

With this change:

```patch
diff --git i/src/lib.rs w/src/lib.rs
index 7af31b6..cff4b10 100644
--- i/src/lib.rs
+++ w/src/lib.rs
@@ -102,7 +102,7 @@ impl<'a, 'cx> Folder for Overflower<'a, 'cx> {
 }
 
 fn tag_method(o: &mut Overflower, name: &str, receiver: P<Expr>, args: Vec<P<Expr>>) -> P<Expr> {
-    let rec = receiver.map(|r| fold::noop_fold_expr(r, o));
+    let rec = receiver.map(|r| o.fold_expr(P(r)).unwrap());
     let fn_name = o.cx.ident_of(&format!("{}_{}", name, o.mode));
     let args_expanded = args.into_iter().map(|a| a.map(|e| fold::noop_fold_expr(e, o))).collect();
     o.cx.expr_method_call(DUMMY_SP, rec, fn_name, args_expanded)
```

it is correctly expanded:

```rust
fn main() { 
    let i = 1u8.sub_wrap(1).sub_wrap(2); 
}
```

The args are folded using the same `noop_fold_expr` as well, not sure if that needs to be changed (at least it still compiles and tests are green).
I did not submit a PR (yet), because I just `unwrap`. Do we need proper error handling there? Is it possible this fails at all?

**Comment by llogiq** [comment]
Thanks, fixed.

**Comment by llogiq** [comment]
Oh, btw. `unwrap()` isn't problematic in this example, but it's not necessary, because we can simply omit the `.map(..)`.

**Comment by badboy** [comment]
\o/ Saw it.
